version: '2'
services:
  zookeeper:
    image: zookeeper
    user: "0:0"
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOOKEEPER_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./tmp/zoo1/data:/data
      - ./tmp/zoo1/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:6.2.4
    user: "0:0"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/data:/var/lib/kafka/data
    links:
      - zookeeper